# Generated by Django 4.2 on 2024-08-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Pacientes',
        ),
    ]
