# Generated by Django 4.2 on 2024-09-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_paciente_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_pacientes/'),
        ),
    ]
